2019-10-13 21:34:19,815 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:34:19,816 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:34:19,816 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:34:19,817 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:34:20,083 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:34:20,544 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:34:20,544 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:34:20,544 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:34:20,800 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:34:21,296 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 500b7741fcdb:8069 
2019-10-13 21:35:11,803 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 21:35:11,804 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 21:38:19,507 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:38:19,508 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:38:19,508 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:38:19,509 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:38:19,647 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:38:19,797 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:38:19,797 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:38:19,798 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:38:20,042 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:38:20,058 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on a51969301e4d:8069 
2019-10-13 21:39:13,596 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 21:39:13,661 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 21:39:13,686 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 21:39:13,696 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 21:39:13,754 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 21:39:13,980 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 21:39:13,985 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 21:39:14,029 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:14] "GET /web/ HTTP/1.1" 303 - 12 0.021 0.409
2019-10-13 21:39:15,085 1 INFO odoo odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2019-10-13 21:39:15,092 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/login HTTP/1.1" 200 - 219 0.194 0.863
2019-10-13 21:39:15,145 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/ba/bad99cf68aa13183ad31ee9d9cd107ec2ae68257 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 246

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(246,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/ba/bad99cf68aa13183ad31ee9d9cd107ec2ae68257'
2019-10-13 21:39:15,147 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/75/759547880e3173667848f67bf6d5eeec95ad3bec 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 251

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(251,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/75/759547880e3173667848f67bf6d5eeec95ad3bec'
2019-10-13 21:39:15,156 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/content/255-0a04e36/web.assets_frontend.0.css HTTP/1.1" 200 - 6 0.012 0.027
2019-10-13 21:39:15,158 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/content/256-0a04e36/web.assets_frontend.js HTTP/1.1" 200 - 5 0.012 0.024
2019-10-13 21:39:15,161 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/content/246-5086be3/web.assets_common.0.css HTTP/1.1" 200 - 11 0.018 0.028
2019-10-13 21:39:15,164 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/content/251-5086be3/web.assets_common.js HTTP/1.1" 200 - 5 0.008 0.036
2019-10-13 21:39:15,181 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:15] "GET /web/binary/company_logo HTTP/1.1" 200 - 2 0.002 0.005
2019-10-13 21:39:17,362 1 INFO odoo odoo.addons.base.models.res_users: Login successful for db:odoo login:odoo from 172.19.0.1 
2019-10-13 21:39:17,389 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:17] "POST /web/login HTTP/1.1" 200 - 28 0.035 0.126
2019-10-13 21:39:17,588 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/a3/a330920abcef2433621d6bb985bc24828d77f77b 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f8b3d7046a8>, 2, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 244

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(244,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/a3/a330920abcef2433621d6bb985bc24828d77f77b'
2019-10-13 21:39:17,589 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/b8/b8f9001425cfd0ef0315797909281b912817643a 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7f8b3d7046a8>, 2, False, ('en_US',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 244

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(244,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/b8/b8f9001425cfd0ef0315797909281b912817643a'
2019-10-13 21:39:18,114 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:18] "GET /web HTTP/1.1" 200 - 297 0.240 0.452
2019-10-13 21:39:27,171 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:27] "GET /web HTTP/1.1" 200 - 9 0.008 0.016
2019-10-13 21:39:27,352 1 INFO ? werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:27] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 21:39:33,374 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:33] "GET / HTTP/1.1" 200 - 1 0.001 0.004
2019-10-13 21:39:33,421 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:39:33] "GET /web HTTP/1.1" 200 - 9 0.006 0.017
2019-10-13 21:41:46,769 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 21:41:46,769 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 21:42:02,951 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:42:02,952 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:42:02,952 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:42:02,953 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:42:03,159 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:42:03,407 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:42:03,407 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:42:03,407 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:42:03,659 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:42:03,732 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 759bc1d1e7ce:8069 
2019-10-13 21:42:08,581 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 21:42:08,588 1 INFO odoo odoo.sql_db: Connection to the database failed 
2019-10-13 21:42:08,592 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:42:08] "GET /web HTTP/1.1" 302 - 0 0.000 0.008
2019-10-13 21:42:08,614 1 INFO ? odoo.http: Generating nondb routing 
2019-10-13 21:42:08,745 1 INFO ? werkzeug: 172.19.0.1 - - [13/Oct/2019 21:42:08] "GET /web/database/selector HTTP/1.1" 200 - 2 0.007 0.141
2019-10-13 21:42:18,315 1 INFO None odoo.service.db: Create database `odoo`. 
2019-10-13 21:42:21,929 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 21:42:22,122 1 INFO odoo odoo.modules.registry: module base: creating or updating database tables 
2019-10-13 21:42:25,377 1 INFO odoo odoo.models: Computing parent_path for table ir_ui_menu... 
2019-10-13 21:42:34,738 1 INFO odoo odoo.models: Computing parent_path for table res_partner_category... 
2019-10-13 21:42:39,333 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2019-10-13 21:42:39,344 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.related_field_id 
2019-10-13 21:42:39,768 1 INFO odoo odoo.models: Storing computed values of ir.actions.server.model_name 
2019-10-13 21:42:39,931 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_name 
2019-10-13 21:42:39,932 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_model_name 
2019-10-13 21:42:39,965 1 INFO odoo odoo.models: Storing computed values of ir.cron.cron_name 
2019-10-13 21:42:40,096 1 INFO odoo odoo.models: Storing computed values of ir.rule.global 
2019-10-13 21:42:40,352 1 INFO odoo odoo.models: Storing computed values of ir.module.module.menus_by_module 
2019-10-13 21:42:40,355 1 INFO odoo odoo.models: Storing computed values of ir.module.module.reports_by_module 
2019-10-13 21:42:40,357 1 INFO odoo odoo.models: Storing computed values of ir.module.module.views_by_module 
2019-10-13 21:42:40,652 1 INFO odoo odoo.models: Storing computed values of res.partner.display_name 
2019-10-13 21:42:40,675 1 INFO odoo odoo.models: Storing computed values of res.partner.partner_share 
2019-10-13 21:42:40,680 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_partner_id 
2019-10-13 21:42:40,681 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_company_name 
2019-10-13 21:42:40,742 1 INFO odoo odoo.models: Storing computed values of res.partner.bank.sanitized_acc_number 
2019-10-13 21:42:40,817 1 INFO odoo odoo.models: Storing computed values of res.currency.decimal_places 
2019-10-13 21:42:40,884 1 INFO odoo odoo.models: Storing computed values of res.company.logo_web 
2019-10-13 21:42:40,901 1 INFO odoo odoo.models: Storing computed values of res.company.email 
2019-10-13 21:42:40,903 1 INFO odoo odoo.models: Storing computed values of res.company.phone 
2019-10-13 21:42:41,017 1 INFO odoo odoo.models: Storing computed values of res.users.share 
2019-10-13 21:42:42,114 1 INFO odoo odoo.modules.loading: loading base/data/res.lang.csv 
2019-10-13 21:42:42,342 1 INFO odoo odoo.modules.loading: loading base/data/res_lang_data.xml 
2019-10-13 21:42:42,370 1 INFO odoo odoo.modules.loading: loading base/data/res_partner_data.xml 
2019-10-13 21:42:42,820 1 INFO odoo odoo.modules.loading: loading base/data/res_company_data.xml 
2019-10-13 21:42:42,886 1 INFO odoo odoo.modules.loading: loading base/data/res_users_data.xml 
2019-10-13 21:42:43,181 1 INFO odoo odoo.modules.loading: loading base/data/report_paperformat_data.xml 
2019-10-13 21:42:43,203 1 INFO odoo odoo.modules.loading: loading base/data/res_currency_data.xml 
2019-10-13 21:42:44,332 1 INFO odoo odoo.modules.loading: loading base/data/res_country_data.xml 
2019-10-13 21:42:48,737 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_data.xml 
2019-10-13 21:42:48,784 1 INFO odoo odoo.modules.loading: loading base/security/base_groups.xml 
2019-10-13 21:42:49,167 1 INFO odoo odoo.modules.loading: loading base/security/base_security.xml 
2019-10-13 21:42:49,477 1 INFO odoo odoo.modules.loading: loading base/views/base_menus.xml 
2019-10-13 21:42:49,764 1 INFO odoo odoo.modules.loading: loading base/views/res_config_views.xml 
2019-10-13 21:42:49,819 1 INFO odoo odoo.modules.loading: loading base/data/res.country.state.csv 
2019-10-13 21:42:50,487 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 21:42:50,488 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 21:42:50,718 1 INFO odoo odoo.modules.loading: loading base/views/ir_actions_views.xml 
2019-10-13 21:42:51,374 1 INFO odoo odoo.modules.loading: loading base/views/ir_config_parameter_views.xml 
2019-10-13 21:42:51,481 1 INFO odoo odoo.modules.loading: loading base/views/ir_cron_views.xml 
2019-10-13 21:42:51,660 1 INFO odoo odoo.modules.loading: loading base/views/ir_filters_views.xml 
2019-10-13 21:42:51,788 1 INFO odoo odoo.modules.loading: loading base/views/ir_mail_server_views.xml 
2019-10-13 21:42:51,923 1 INFO odoo odoo.modules.loading: loading base/views/ir_model_views.xml 
2019-10-13 21:42:52,723 1 INFO odoo odoo.modules.loading: loading base/views/ir_attachment_views.xml 
2019-10-13 21:42:52,874 1 INFO odoo odoo.modules.loading: loading base/views/ir_rule_views.xml 
2019-10-13 21:42:52,992 1 INFO odoo odoo.modules.loading: loading base/views/ir_sequence_views.xml 
2019-10-13 21:42:53,139 1 INFO odoo odoo.modules.loading: loading base/views/ir_translation_views.xml 
2019-10-13 21:42:53,283 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_menu_views.xml 
2019-10-13 21:42:53,416 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_view_views.xml 
2019-10-13 21:42:53,628 1 INFO odoo odoo.modules.loading: loading base/views/ir_default_views.xml 
2019-10-13 21:42:53,755 1 INFO odoo odoo.modules.loading: loading base/data/ir_cron_data.xml 
2019-10-13 21:42:53,827 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_report.xml 
2019-10-13 21:42:53,841 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_templates.xml 
2019-10-13 21:42:53,884 1 INFO odoo odoo.modules.loading: loading base/views/ir_logging_views.xml 
2019-10-13 21:42:54,008 1 INFO odoo odoo.modules.loading: loading base/views/ir_qweb_widget_templates.xml 
2019-10-13 21:42:54,072 1 INFO odoo odoo.modules.loading: loading base/views/ir_module_views.xml 
2019-10-13 21:42:54,350 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_category_data.xml 
2019-10-13 21:42:54,565 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_module.xml 
2019-10-13 21:42:54,782 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_reports.xml 
2019-10-13 21:42:54,798 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_report_templates.xml 
2019-10-13 21:42:54,837 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_update_views.xml 
2019-10-13 21:42:54,903 1 INFO odoo odoo.modules.loading: loading base/wizard/base_language_install_views.xml 
2019-10-13 21:42:54,978 1 INFO odoo odoo.modules.loading: loading base/wizard/base_import_language_views.xml 
2019-10-13 21:42:55,034 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_upgrade_views.xml 
2019-10-13 21:42:55,131 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_uninstall_views.xml 
2019-10-13 21:42:55,178 1 INFO odoo odoo.modules.loading: loading base/wizard/base_export_language_views.xml 
2019-10-13 21:42:55,243 1 INFO odoo odoo.modules.loading: loading base/wizard/base_update_translations_views.xml 
2019-10-13 21:42:55,302 1 INFO odoo odoo.modules.loading: loading base/wizard/base_partner_merge_views.xml 
2019-10-13 21:42:55,369 1 INFO odoo odoo.modules.loading: loading base/data/ir_actions_data.xml 
2019-10-13 21:42:55,386 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_failure_data.xml 
2019-10-13 21:42:55,450 1 INFO odoo odoo.modules.loading: loading base/views/res_company_views.xml 
2019-10-13 21:42:55,706 1 INFO odoo odoo.modules.loading: loading base/views/res_lang_views.xml 
2019-10-13 21:42:55,833 1 INFO odoo odoo.modules.loading: loading base/views/res_partner_views.xml 
2019-10-13 21:42:56,503 1 INFO odoo odoo.modules.loading: loading base/views/res_bank_views.xml 
2019-10-13 21:42:56,696 1 INFO odoo odoo.modules.loading: loading base/views/res_country_views.xml 
2019-10-13 21:42:56,911 1 INFO odoo odoo.modules.loading: loading base/views/res_currency_views.xml 
2019-10-13 21:42:57,179 1 INFO odoo odoo.modules.loading: loading base/views/res_users_views.xml 
2019-10-13 21:42:57,870 1 INFO odoo odoo.modules.loading: loading base/views/ir_property_views.xml 
2019-10-13 21:42:58,002 1 INFO odoo odoo.modules.loading: loading base/views/res_config_settings_views.xml 
2019-10-13 21:42:58,046 1 INFO odoo odoo.modules.loading: loading base/views/report_paperformat_views.xml 
2019-10-13 21:42:58,172 1 INFO odoo odoo.modules.loading: loading base/views/onboarding_views.xml 
2019-10-13 21:42:58,368 1 INFO odoo odoo.modules.loading: loading base/security/ir.model.access.csv 
2019-10-13 21:42:59,188 1 INFO odoo odoo.modules.loading: 1 modules loaded in 37.26s, 0 queries 
2019-10-13 21:42:59,274 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 21:42:59,276 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.19.0.1 
2019-10-13 21:43:00,365 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 21:43:00,610 1 INFO odoo odoo.modules.registry: module web: creating or updating database tables 
2019-10-13 21:43:28,960 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:43:28,961 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:43:28,961 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:43:28,962 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:43:29,086 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:43:29,232 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:43:29,232 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:43:29,233 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:43:29,483 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:43:29,498 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on ce78d5e93c1f:8069 
2019-10-13 21:43:47,654 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 21:43:47,746 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 21:43:47,772 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 21:43:47,781 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 21:43:47,854 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.07s, 0 queries 
2019-10-13 21:43:48,076 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 21:43:48,081 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 21:43:48,130 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:43:48] "GET / HTTP/1.1" 200 - 12 0.027 0.445
2019-10-13 21:43:48,164 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:43:48] "GET /web HTTP/1.1" 303 - 1 0.000 0.003
2019-10-13 21:43:48,574 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:43:48] "GET /web/login HTTP/1.1" 200 - 149 0.130 0.275
2019-10-13 21:43:51,181 1 INFO odoo odoo.addons.base.models.res_users: Login successful for db:odoo login:odoo from 172.19.0.1 
2019-10-13 21:43:51,203 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:43:51] "POST /web/login HTTP/1.1" 200 - 28 0.041 0.120
2019-10-13 21:43:51,811 1 INFO odoo werkzeug: 172.19.0.1 - - [13/Oct/2019 21:43:51] "GET /web HTTP/1.1" 200 - 226 0.219 0.357
2019-10-13 21:44:51,126 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 21:44:51,126 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 21:45:23,667 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:45:23,668 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:45:23,668 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:45:23,669 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:45:23,806 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:45:23,967 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:45:23,967 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:45:23,967 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:45:24,218 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:45:24,236 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on f1ac8c6f0f83:8069 
2019-10-13 21:45:29,581 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 21:45:29,611 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 21:45:29,635 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 21:45:29,644 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 21:45:29,705 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 21:45:29,941 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 21:45:29,945 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 21:45:30,820 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:30] "GET /web HTTP/1.1" 200 - 321 0.295 0.941
2019-10-13 21:45:30,904 1 INFO ? werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:30] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 21:45:35,463 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web HTTP/1.1" 200 - 9 0.008 0.019
2019-10-13 21:45:35,513 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/ba/bad99cf68aa13183ad31ee9d9cd107ec2ae68257 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 246

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(246,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/ba/bad99cf68aa13183ad31ee9d9cd107ec2ae68257'
2019-10-13 21:45:35,525 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/20/20d9b299afcabf8f8e526c5a4c245fac12f65294 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 247

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(247,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/20/20d9b299afcabf8f8e526c5a4c245fac12f65294'
2019-10-13 21:45:35,530 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/29/29d97078ab599ae3a41d6463316d2aeb703f00f7 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 248

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(248,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/29/29d97078ab599ae3a41d6463316d2aeb703f00f7'
2019-10-13 21:45:35,531 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/1b/1b01b433fdf56f4efc7ea5ee10c1060c7d341c95 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 250

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(250,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/1b/1b01b433fdf56f4efc7ea5ee10c1060c7d341c95'
2019-10-13 21:45:35,537 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/a6/a6a5d68263ba6b79b814865166e7ea35c21ff6cc 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 249

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(249,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/a6/a6a5d68263ba6b79b814865166e7ea35c21ff6cc'
2019-10-13 21:45:35,537 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/246-5086be3/web.assets_common.0.css HTTP/1.1" 200 - 7 0.008 0.044
2019-10-13 21:45:35,541 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/75/759547880e3173667848f67bf6d5eeec95ad3bec 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 251

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(251,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/75/759547880e3173667848f67bf6d5eeec95ad3bec'
2019-10-13 21:45:35,541 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/247-a0aa1fa/web.assets_backend.0.css HTTP/1.1" 200 - 4 0.010 0.045
2019-10-13 21:45:35,542 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/248-a0aa1fa/web.assets_backend.1.css HTTP/1.1" 200 - 4 0.011 0.043
2019-10-13 21:45:35,544 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/250-447701b/web_editor.assets_editor.0.css HTTP/1.1" 200 - 4 0.009 0.045
2019-10-13 21:45:35,546 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/249-4f411d5/web_editor.summernote.0.css HTTP/1.1" 200 - 4 0.006 0.048
2019-10-13 21:45:35,552 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/251-5086be3/web.assets_common.js HTTP/1.1" 200 - 4 0.006 0.051
2019-10-13 21:45:35,560 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/32/3295593f39ee83a4619914bde09df447cadbf929 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 252

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(252,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/32/3295593f39ee83a4619914bde09df447cadbf929'
2019-10-13 21:45:35,564 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/252-a0aa1fa/web.assets_backend.js HTTP/1.1" 200 - 4 0.004 0.010
2019-10-13 21:45:35,573 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/ec/ec1f61be8a7a33a582a7db19cbff2dc82a73212c 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 254

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(254,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/ec/ec1f61be8a7a33a582a7db19cbff2dc82a73212c'
2019-10-13 21:45:35,574 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/filestore/odoo/e2/e215e6ea4eebea7e9b85a658ea51ed08cb42bcf0 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1039, in get
    value = self._data[key][field][record._ids[0]]
KeyError: 253

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 981, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 1041, in get
    raise CacheMiss(record, field)
odoo.exceptions.CacheMiss: ('ir.attachment(253,).datas', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 113, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/odoo/e2/e215e6ea4eebea7e9b85a658ea51ed08cb42bcf0'
2019-10-13 21:45:35,576 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/254-447701b/web_editor.assets_editor.js HTTP/1.1" 200 - 4 0.004 0.011
2019-10-13 21:45:35,578 1 INFO odoo werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/content/253-4f411d5/web_editor.summernote.js HTTP/1.1" 200 - 4 0.004 0.016
2019-10-13 21:45:35,591 1 INFO ? werkzeug: 172.20.0.1 - - [13/Oct/2019 21:45:35] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 21:47:05,631 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 21:47:05,631 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 21:55:25,823 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 21:55:25,839 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 21:55:25,839 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 21:55:25,840 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 21:55:26,128 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 21:55:26,378 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 21:55:26,379 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 21:55:26,379 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 21:55:26,726 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 21:55:26,774 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 31cbf651b7af:8069 
2019-10-13 21:55:31,300 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 21:55:31,432 1 INFO ? odoo.http: Generating nondb routing 
2019-10-13 21:55:31,451 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 21:55:31] "GET / HTTP/1.1" 200 - 1 0.005 0.144
2019-10-13 21:55:31,500 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 21:55:31] "GET /web HTTP/1.1" 303 - 2 0.009 0.016
2019-10-13 21:55:31,679 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 21:55:31] "GET /web/database/selector HTTP/1.1" 200 - 2 0.006 0.167
2019-10-13 21:55:39,904 1 INFO None odoo.service.db: Create database `odoo`. 
2019-10-13 21:55:43,855 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 21:55:44,053 1 INFO odoo odoo.modules.registry: module base: creating or updating database tables 
2019-10-13 21:55:46,910 1 INFO odoo odoo.models: Computing parent_path for table ir_ui_menu... 
2019-10-13 21:55:56,434 1 INFO odoo odoo.models: Computing parent_path for table res_partner_category... 
2019-10-13 21:56:00,919 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2019-10-13 21:56:00,926 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.related_field_id 
2019-10-13 21:56:01,324 1 INFO odoo odoo.models: Storing computed values of ir.actions.server.model_name 
2019-10-13 21:56:01,488 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_name 
2019-10-13 21:56:01,490 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_model_name 
2019-10-13 21:56:01,520 1 INFO odoo odoo.models: Storing computed values of ir.cron.cron_name 
2019-10-13 21:56:01,675 1 INFO odoo odoo.models: Storing computed values of ir.rule.global 
2019-10-13 21:56:01,977 1 INFO odoo odoo.models: Storing computed values of ir.module.module.menus_by_module 
2019-10-13 21:56:01,980 1 INFO odoo odoo.models: Storing computed values of ir.module.module.reports_by_module 
2019-10-13 21:56:01,983 1 INFO odoo odoo.models: Storing computed values of ir.module.module.views_by_module 
2019-10-13 21:56:02,292 1 INFO odoo odoo.models: Storing computed values of res.partner.display_name 
2019-10-13 21:56:02,314 1 INFO odoo odoo.models: Storing computed values of res.partner.partner_share 
2019-10-13 21:56:02,319 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_partner_id 
2019-10-13 21:56:02,320 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_company_name 
2019-10-13 21:56:02,387 1 INFO odoo odoo.models: Storing computed values of res.partner.bank.sanitized_acc_number 
2019-10-13 21:56:02,471 1 INFO odoo odoo.models: Storing computed values of res.currency.decimal_places 
2019-10-13 21:56:02,537 1 INFO odoo odoo.models: Storing computed values of res.company.logo_web 
2019-10-13 21:56:02,556 1 INFO odoo odoo.models: Storing computed values of res.company.email 
2019-10-13 21:56:02,558 1 INFO odoo odoo.models: Storing computed values of res.company.phone 
2019-10-13 21:56:02,675 1 INFO odoo odoo.models: Storing computed values of res.users.share 
2019-10-13 21:56:03,553 1 INFO odoo odoo.modules.loading: loading base/data/res.lang.csv 
2019-10-13 21:56:03,748 1 INFO odoo odoo.modules.loading: loading base/data/res_lang_data.xml 
2019-10-13 21:56:03,774 1 INFO odoo odoo.modules.loading: loading base/data/res_partner_data.xml 
2019-10-13 21:56:04,135 1 INFO odoo odoo.modules.loading: loading base/data/res_company_data.xml 
2019-10-13 21:56:04,180 1 INFO odoo odoo.modules.loading: loading base/data/res_users_data.xml 
2019-10-13 21:56:04,460 1 INFO odoo odoo.modules.loading: loading base/data/report_paperformat_data.xml 
2019-10-13 21:56:04,482 1 INFO odoo odoo.modules.loading: loading base/data/res_currency_data.xml 
2019-10-13 21:56:05,539 1 INFO odoo odoo.modules.loading: loading base/data/res_country_data.xml 
2019-10-13 21:56:10,039 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_data.xml 
2019-10-13 21:56:10,092 1 INFO odoo odoo.modules.loading: loading base/security/base_groups.xml 
2019-10-13 21:56:10,580 1 INFO odoo odoo.modules.loading: loading base/security/base_security.xml 
2019-10-13 21:56:10,892 1 INFO odoo odoo.modules.loading: loading base/views/base_menus.xml 
2019-10-13 21:56:11,208 1 INFO odoo odoo.modules.loading: loading base/views/res_config_views.xml 
2019-10-13 21:56:11,266 1 INFO odoo odoo.modules.loading: loading base/data/res.country.state.csv 
2019-10-13 21:56:12,172 1 INFO odoo odoo.modules.loading: loading base/views/ir_actions_views.xml 
2019-10-13 21:56:12,794 1 INFO odoo odoo.modules.loading: loading base/views/ir_config_parameter_views.xml 
2019-10-13 21:56:12,905 1 INFO odoo odoo.modules.loading: loading base/views/ir_cron_views.xml 
2019-10-13 21:56:13,101 1 INFO odoo odoo.modules.loading: loading base/views/ir_filters_views.xml 
2019-10-13 21:56:13,230 1 INFO odoo odoo.modules.loading: loading base/views/ir_mail_server_views.xml 
2019-10-13 21:56:13,349 1 INFO odoo odoo.modules.loading: loading base/views/ir_model_views.xml 
2019-10-13 21:56:14,091 1 INFO odoo odoo.modules.loading: loading base/views/ir_attachment_views.xml 
2019-10-13 21:56:14,245 1 INFO odoo odoo.modules.loading: loading base/views/ir_rule_views.xml 
2019-10-13 21:56:14,382 1 INFO odoo odoo.modules.loading: loading base/views/ir_sequence_views.xml 
2019-10-13 21:56:14,525 1 INFO odoo odoo.modules.loading: loading base/views/ir_translation_views.xml 
2019-10-13 21:56:14,680 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_menu_views.xml 
2019-10-13 21:56:14,886 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_view_views.xml 
2019-10-13 21:56:15,102 1 INFO odoo odoo.modules.loading: loading base/views/ir_default_views.xml 
2019-10-13 21:56:15,233 1 INFO odoo odoo.modules.loading: loading base/data/ir_cron_data.xml 
2019-10-13 21:56:15,260 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_report.xml 
2019-10-13 21:56:15,276 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_templates.xml 
2019-10-13 21:56:15,319 1 INFO odoo odoo.modules.loading: loading base/views/ir_logging_views.xml 
2019-10-13 21:56:15,448 1 INFO odoo odoo.modules.loading: loading base/views/ir_qweb_widget_templates.xml 
2019-10-13 21:56:15,514 1 INFO odoo odoo.modules.loading: loading base/views/ir_module_views.xml 
2019-10-13 21:56:15,814 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_category_data.xml 
2019-10-13 21:56:16,038 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_module.xml 
2019-10-13 21:56:16,274 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_reports.xml 
2019-10-13 21:56:16,288 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_report_templates.xml 
2019-10-13 21:56:16,327 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_update_views.xml 
2019-10-13 21:56:16,385 1 INFO odoo odoo.modules.loading: loading base/wizard/base_language_install_views.xml 
2019-10-13 21:56:16,456 1 INFO odoo odoo.modules.loading: loading base/wizard/base_import_language_views.xml 
2019-10-13 21:56:16,516 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_upgrade_views.xml 
2019-10-13 21:56:16,609 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_uninstall_views.xml 
2019-10-13 21:56:16,658 1 INFO odoo odoo.modules.loading: loading base/wizard/base_export_language_views.xml 
2019-10-13 21:56:16,728 1 INFO odoo odoo.modules.loading: loading base/wizard/base_update_translations_views.xml 
2019-10-13 21:56:16,797 1 INFO odoo odoo.modules.loading: loading base/wizard/base_partner_merge_views.xml 
2019-10-13 21:56:16,873 1 INFO odoo odoo.modules.loading: loading base/data/ir_actions_data.xml 
2019-10-13 21:56:16,896 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_failure_data.xml 
2019-10-13 21:56:16,958 1 INFO odoo odoo.modules.loading: loading base/views/res_company_views.xml 
2019-10-13 21:56:17,216 1 INFO odoo odoo.modules.loading: loading base/views/res_lang_views.xml 
2019-10-13 21:56:17,346 1 INFO odoo odoo.modules.loading: loading base/views/res_partner_views.xml 
2019-10-13 21:56:17,988 1 INFO odoo odoo.modules.loading: loading base/views/res_bank_views.xml 
2019-10-13 21:56:18,195 1 INFO odoo odoo.modules.loading: loading base/views/res_country_views.xml 
2019-10-13 21:56:18,410 1 INFO odoo odoo.modules.loading: loading base/views/res_currency_views.xml 
2019-10-13 21:56:18,675 1 INFO odoo odoo.modules.loading: loading base/views/res_users_views.xml 
2019-10-13 21:56:19,363 1 INFO odoo odoo.modules.loading: loading base/views/ir_property_views.xml 
2019-10-13 21:56:19,476 1 INFO odoo odoo.modules.loading: loading base/views/res_config_settings_views.xml 
2019-10-13 21:56:19,511 1 INFO odoo odoo.modules.loading: loading base/views/report_paperformat_views.xml 
2019-10-13 21:56:19,615 1 INFO odoo odoo.modules.loading: loading base/views/onboarding_views.xml 
2019-10-13 21:56:19,778 1 INFO odoo odoo.modules.loading: loading base/security/ir.model.access.csv 
2019-10-13 21:56:20,754 1 INFO odoo odoo.modules.loading: 1 modules loaded in 36.90s, 0 queries 
2019-10-13 21:56:20,844 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 21:56:20,847 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 21:56:21,909 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 21:56:22,149 1 INFO odoo odoo.modules.registry: module web: creating or updating database tables 
2019-10-13 21:56:24,337 1 INFO odoo odoo.modules.loading: loading web/security/ir.model.access.csv 
2019-10-13 21:56:24,356 1 INFO odoo odoo.modules.loading: loading web/views/webclient_templates.xml 
2019-10-13 21:56:24,856 1 INFO odoo odoo.modules.loading: loading web/views/report_templates.xml 
2019-10-13 21:56:25,344 1 INFO odoo odoo.modules.loading: loading web/data/res_company.xml 
2019-10-13 21:56:25,360 1 INFO odoo odoo.modules.loading: loading web/data/report_layout.xml 
2019-10-13 21:56:25,729 1 INFO odoo odoo.modules.registry: module base_import: creating or updating database tables 
2019-10-13 21:56:29,947 1 INFO odoo odoo.modules.loading: loading base_import/security/ir.model.access.csv 
2019-10-13 21:56:30,049 1 INFO odoo odoo.modules.loading: loading base_import/views/base_import_templates.xml 
2019-10-13 21:56:30,342 1 INFO odoo odoo.modules.registry: module web_diagram: creating or updating database tables 
2019-10-13 21:56:30,355 1 INFO odoo odoo.modules.loading: loading web_diagram/views/web_diagram_templates.xml 
2019-10-13 21:56:30,802 1 INFO odoo odoo.modules.registry: module web_editor: creating or updating database tables 
2019-10-13 21:56:31,367 1 INFO odoo odoo.modules.loading: loading web_editor/security/ir.model.access.csv 
2019-10-13 21:56:31,392 1 INFO odoo odoo.modules.loading: loading web_editor/views/editor.xml 
2019-10-13 21:56:31,898 1 INFO odoo odoo.modules.loading: loading web_editor/views/iframe.xml 
2019-10-13 21:56:31,959 1 INFO odoo odoo.modules.loading: loading web_editor/views/snippets.xml 
2019-10-13 21:56:32,188 1 INFO odoo odoo.modules.registry: module web_kanban_gauge: creating or updating database tables 
2019-10-13 21:56:32,202 1 INFO odoo odoo.modules.loading: loading web_kanban_gauge/views/web_kanban_gauge_templates.xml 
2019-10-13 21:56:32,531 1 INFO odoo odoo.modules.registry: module web_settings_dashboard: creating or updating database tables 
2019-10-13 21:56:32,595 1 INFO odoo odoo.modules.loading: loading web_settings_dashboard/views/dashboard_views.xml 
2019-10-13 21:56:32,621 1 INFO odoo odoo.modules.loading: loading web_settings_dashboard/views/dashboard_templates.xml 
2019-10-13 21:56:32,968 1 INFO odoo odoo.modules.registry: module web_tour: creating or updating database tables 
2019-10-13 21:56:33,151 1 INFO odoo odoo.modules.loading: loading web_tour/security/ir.model.access.csv 
2019-10-13 21:56:33,178 1 INFO odoo odoo.modules.loading: loading web_tour/security/ir.rule.csv 
2019-10-13 21:56:33,217 1 INFO odoo odoo.modules.loading: loading web_tour/views/tour_templates.xml 
2019-10-13 21:56:33,340 1 INFO odoo odoo.modules.loading: loading web_tour/views/tour_views.xml 
2019-10-13 21:56:33,657 1 INFO odoo odoo.modules.registry: module iap: creating or updating database tables 
2019-10-13 21:56:33,876 1 INFO odoo odoo.modules.loading: loading iap/security/ir.model.access.csv 
2019-10-13 21:56:33,906 1 INFO odoo odoo.modules.loading: loading iap/security/ir_rule.xml 
2019-10-13 21:56:33,934 1 INFO odoo odoo.modules.loading: loading iap/views/assets.xml 
2019-10-13 21:56:34,014 1 INFO odoo odoo.modules.loading: loading iap/views/iap_views.xml 
2019-10-13 21:56:34,158 1 INFO odoo odoo.modules.loading: 9 modules loaded in 12.25s, 0 queries 
2019-10-13 21:56:34,476 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 21:56:34,747 1 INFO odoo odoo.addons.base.models.res_users: Login successful for db:odoo login:odoo from 172.21.0.1 
2019-10-13 21:56:34,764 1 INFO odoo odoo.modules.registry: Registry changed, signaling through the database 
2019-10-13 21:56:34,773 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 21:56:34] "POST /web/database/create HTTP/1.1" 303 - 25404 38.289 16.636
2019-10-13 21:56:34,784 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 21:56:38,729 1 INFO odoo odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2019-10-13 21:56:38,733 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 21:56:38] "GET /web/ HTTP/1.1" 200 - 605 0.538 3.415
2019-10-13 21:57:15,713 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 21:57:15] "GET /web/ HTTP/1.1" 200 - 294 0.258 0.454
2019-10-13 21:57:15,739 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 21:57:15] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 21:57:26,924 1 INFO odoo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2019-10-13 21:57:26,989 1 INFO odoo odoo.addons.base.models.ir_attachment: filestore gc 253 checked, 0 removed 
2019-10-13 21:57:27,025 1 INFO odoo odoo.addons.base.models.ir_autovacuum: GC'd 0 user log entries 
2019-10-13 22:04:21,323 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:04:21,323 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 22:06:44,965 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 22:06:44,965 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 22:06:44,965 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 22:06:44,966 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 22:06:45,100 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 22:06:45,247 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 00cdefb6642e:8069 
2019-10-13 22:07:34,467 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 22:07:34,491 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:07:34,517 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:07:34,530 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:07:34,589 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 22:07:34,809 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:07:34,814 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:07:35,666 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:07:35] "GET /web/ HTTP/1.1" 200 - 321 0.303 0.894
2019-10-13 22:07:35,702 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:07:35] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:08:18,308 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:08:18,308 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 22:08:48,299 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 22:08:48,299 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 22:08:48,299 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 22:08:48,300 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 22:08:48,436 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 22:08:48,576 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 22:08:48,577 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 22:08:48,577 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 22:08:48,825 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 22:08:48,836 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on c4748ea84f87:8069 
2019-10-13 22:08:52,235 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 22:08:52,264 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:08:52,290 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:08:52,299 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:08:52,356 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 22:08:52,584 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:08:52,590 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:08:53,423 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:08:53] "GET /web/ HTTP/1.1" 200 - 321 0.293 0.892
2019-10-13 22:08:53,453 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:08:53] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:08:57,514 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:08:57,515 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 22:10:23,848 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 22:10:23,849 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 22:10:23,849 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 22:10:23,850 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 22:10:23,980 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 22:10:24,136 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 22:10:24,136 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 22:10:24,136 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 22:10:24,389 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 22:10:24,407 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0f839b888d9f:8069 
2019-10-13 22:10:33,574 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 22:10:33,591 1 INFO ? odoo.http: Generating nondb routing 
2019-10-13 22:10:33,610 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:10:33] "GET / HTTP/1.1" 200 - 1 0.003 0.031
2019-10-13 22:10:33,654 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:10:33] "GET /web HTTP/1.1" 303 - 2 0.005 0.011
2019-10-13 22:10:33,792 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:10:33] "GET /web/database/selector HTTP/1.1" 200 - 2 0.006 0.127
2019-10-13 22:10:43,707 1 INFO None odoo.service.db: Create database `postgres`. 
2019-10-13 22:10:43,713 1 ERROR None odoo.http: database 'postgres' already exists! 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 120, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 448, in dispatch
    return g[exp_method_name](*params)
  File "<decorator-gen-4>", line 2, in exp_create_database
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 40, in if_db_mgt_enabled
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 115, in exp_create_database
    _create_empty_database(db_name)
  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 100, in _create_empty_database
    raise DatabaseExists("database %r already exists!" % (name,))
odoo.service.db.DatabaseExists: database 'postgres' already exists!
2019-10-13 22:10:43,791 1 INFO None werkzeug: 172.21.0.1 - - [13/Oct/2019 22:10:43] "POST /web/database/create HTTP/1.1" 200 - 3 0.009 0.138
2019-10-13 22:10:54,920 1 INFO None odoo.service.db: Create database `odoo`. 
2019-10-13 22:10:58,543 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:10:58,736 1 INFO odoo odoo.modules.registry: module base: creating or updating database tables 
2019-10-13 22:11:01,591 1 INFO odoo odoo.models: Computing parent_path for table ir_ui_menu... 
2019-10-13 22:11:10,251 1 INFO odoo odoo.models: Computing parent_path for table res_partner_category... 
2019-10-13 22:11:15,293 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.relation_field_id 
2019-10-13 22:11:15,303 1 INFO odoo odoo.models: Storing computed values of ir.model.fields.related_field_id 
2019-10-13 22:11:15,700 1 INFO odoo odoo.models: Storing computed values of ir.actions.server.model_name 
2019-10-13 22:11:15,858 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_name 
2019-10-13 22:11:15,860 1 INFO odoo odoo.models: Storing computed values of ir.attachment.res_model_name 
2019-10-13 22:11:15,893 1 INFO odoo odoo.models: Storing computed values of ir.cron.cron_name 
2019-10-13 22:11:16,023 1 INFO odoo odoo.models: Storing computed values of ir.rule.global 
2019-10-13 22:11:16,298 1 INFO odoo odoo.models: Storing computed values of ir.module.module.menus_by_module 
2019-10-13 22:11:16,301 1 INFO odoo odoo.models: Storing computed values of ir.module.module.reports_by_module 
2019-10-13 22:11:16,303 1 INFO odoo odoo.models: Storing computed values of ir.module.module.views_by_module 
2019-10-13 22:11:16,617 1 INFO odoo odoo.models: Storing computed values of res.partner.display_name 
2019-10-13 22:11:16,651 1 INFO odoo odoo.models: Storing computed values of res.partner.partner_share 
2019-10-13 22:11:16,656 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_partner_id 
2019-10-13 22:11:16,658 1 INFO odoo odoo.models: Storing computed values of res.partner.commercial_company_name 
2019-10-13 22:11:16,726 1 INFO odoo odoo.models: Storing computed values of res.partner.bank.sanitized_acc_number 
2019-10-13 22:11:16,796 1 INFO odoo odoo.models: Storing computed values of res.currency.decimal_places 
2019-10-13 22:11:16,859 1 INFO odoo odoo.models: Storing computed values of res.company.logo_web 
2019-10-13 22:11:16,876 1 INFO odoo odoo.models: Storing computed values of res.company.email 
2019-10-13 22:11:16,878 1 INFO odoo odoo.models: Storing computed values of res.company.phone 
2019-10-13 22:11:16,998 1 INFO odoo odoo.models: Storing computed values of res.users.share 
2019-10-13 22:11:17,840 1 INFO odoo odoo.modules.loading: loading base/data/res.lang.csv 
2019-10-13 22:11:18,069 1 INFO odoo odoo.modules.loading: loading base/data/res_lang_data.xml 
2019-10-13 22:11:18,097 1 INFO odoo odoo.modules.loading: loading base/data/res_partner_data.xml 
2019-10-13 22:11:18,497 1 INFO odoo odoo.modules.loading: loading base/data/res_company_data.xml 
2019-10-13 22:11:18,543 1 INFO odoo odoo.modules.loading: loading base/data/res_users_data.xml 
2019-10-13 22:11:18,825 1 INFO odoo odoo.modules.loading: loading base/data/report_paperformat_data.xml 
2019-10-13 22:11:18,849 1 INFO odoo odoo.modules.loading: loading base/data/res_currency_data.xml 
2019-10-13 22:11:19,969 1 INFO odoo odoo.modules.loading: loading base/data/res_country_data.xml 
2019-10-13 22:11:24,471 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_data.xml 
2019-10-13 22:11:24,519 1 INFO odoo odoo.modules.loading: loading base/security/base_groups.xml 
2019-10-13 22:11:24,934 1 INFO odoo odoo.modules.loading: loading base/security/base_security.xml 
2019-10-13 22:11:25,247 1 INFO odoo odoo.modules.loading: loading base/views/base_menus.xml 
2019-10-13 22:11:25,527 1 INFO odoo odoo.modules.loading: loading base/views/res_config_views.xml 
2019-10-13 22:11:25,582 1 INFO odoo odoo.modules.loading: loading base/data/res.country.state.csv 
2019-10-13 22:11:26,422 1 INFO odoo odoo.modules.loading: loading base/views/ir_actions_views.xml 
2019-10-13 22:11:27,067 1 INFO odoo odoo.modules.loading: loading base/views/ir_config_parameter_views.xml 
2019-10-13 22:11:27,175 1 INFO odoo odoo.modules.loading: loading base/views/ir_cron_views.xml 
2019-10-13 22:11:27,355 1 INFO odoo odoo.modules.loading: loading base/views/ir_filters_views.xml 
2019-10-13 22:11:27,494 1 INFO odoo odoo.modules.loading: loading base/views/ir_mail_server_views.xml 
2019-10-13 22:11:27,636 1 INFO odoo odoo.modules.loading: loading base/views/ir_model_views.xml 
2019-10-13 22:11:28,395 1 INFO odoo odoo.modules.loading: loading base/views/ir_attachment_views.xml 
2019-10-13 22:11:28,553 1 INFO odoo odoo.modules.loading: loading base/views/ir_rule_views.xml 
2019-10-13 22:11:28,693 1 INFO odoo odoo.modules.loading: loading base/views/ir_sequence_views.xml 
2019-10-13 22:11:28,834 1 INFO odoo odoo.modules.loading: loading base/views/ir_translation_views.xml 
2019-10-13 22:11:28,993 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_menu_views.xml 
2019-10-13 22:11:29,134 1 INFO odoo odoo.modules.loading: loading base/views/ir_ui_view_views.xml 
2019-10-13 22:11:29,380 1 INFO odoo odoo.modules.loading: loading base/views/ir_default_views.xml 
2019-10-13 22:11:29,519 1 INFO odoo odoo.modules.loading: loading base/data/ir_cron_data.xml 
2019-10-13 22:11:29,547 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_report.xml 
2019-10-13 22:11:29,561 1 INFO odoo odoo.modules.loading: loading base/report/ir_model_templates.xml 
2019-10-13 22:11:29,607 1 INFO odoo odoo.modules.loading: loading base/views/ir_logging_views.xml 
2019-10-13 22:11:29,735 1 INFO odoo odoo.modules.loading: loading base/views/ir_qweb_widget_templates.xml 
2019-10-13 22:11:29,804 1 INFO odoo odoo.modules.loading: loading base/views/ir_module_views.xml 
2019-10-13 22:11:30,108 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_category_data.xml 
2019-10-13 22:11:30,328 1 INFO odoo odoo.modules.loading: loading base/data/ir_module_module.xml 
2019-10-13 22:11:30,558 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_reports.xml 
2019-10-13 22:11:30,571 1 INFO odoo odoo.modules.loading: loading base/report/ir_module_report_templates.xml 
2019-10-13 22:11:30,608 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_update_views.xml 
2019-10-13 22:11:30,667 1 INFO odoo odoo.modules.loading: loading base/wizard/base_language_install_views.xml 
2019-10-13 22:11:30,746 1 INFO odoo odoo.modules.loading: loading base/wizard/base_import_language_views.xml 
2019-10-13 22:11:30,799 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_upgrade_views.xml 
2019-10-13 22:11:30,881 1 INFO odoo odoo.modules.loading: loading base/wizard/base_module_uninstall_views.xml 
2019-10-13 22:11:30,921 1 INFO odoo odoo.modules.loading: loading base/wizard/base_export_language_views.xml 
2019-10-13 22:11:30,979 1 INFO odoo odoo.modules.loading: loading base/wizard/base_update_translations_views.xml 
2019-10-13 22:11:31,030 1 INFO odoo odoo.modules.loading: loading base/wizard/base_partner_merge_views.xml 
2019-10-13 22:11:31,091 1 INFO odoo odoo.modules.loading: loading base/data/ir_actions_data.xml 
2019-10-13 22:11:31,107 1 INFO odoo odoo.modules.loading: loading base/data/ir_demo_failure_data.xml 
2019-10-13 22:11:31,162 1 INFO odoo odoo.modules.loading: loading base/views/res_company_views.xml 
2019-10-13 22:11:31,462 1 INFO odoo odoo.modules.loading: loading base/views/res_lang_views.xml 
2019-10-13 22:11:31,605 1 INFO odoo odoo.modules.loading: loading base/views/res_partner_views.xml 
2019-10-13 22:11:32,241 1 INFO odoo odoo.modules.loading: loading base/views/res_bank_views.xml 
2019-10-13 22:11:32,445 1 INFO odoo odoo.modules.loading: loading base/views/res_country_views.xml 
2019-10-13 22:11:32,664 1 INFO odoo odoo.modules.loading: loading base/views/res_currency_views.xml 
2019-10-13 22:11:32,926 1 INFO odoo odoo.modules.loading: loading base/views/res_users_views.xml 
2019-10-13 22:11:33,494 1 INFO odoo odoo.modules.loading: loading base/views/ir_property_views.xml 
2019-10-13 22:11:33,603 1 INFO odoo odoo.modules.loading: loading base/views/res_config_settings_views.xml 
2019-10-13 22:11:33,640 1 INFO odoo odoo.modules.loading: loading base/views/report_paperformat_views.xml 
2019-10-13 22:11:33,768 1 INFO odoo odoo.modules.loading: loading base/views/onboarding_views.xml 
2019-10-13 22:11:33,956 1 INFO odoo odoo.modules.loading: loading base/security/ir.model.access.csv 
2019-10-13 22:11:34,684 1 INFO odoo odoo.modules.loading: 1 modules loaded in 36.14s, 0 queries 
2019-10-13 22:11:34,772 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:11:34,774 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:11:35,898 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:11:36,141 1 INFO odoo odoo.modules.registry: module web: creating or updating database tables 
2019-10-13 22:11:38,353 1 INFO odoo odoo.modules.loading: loading web/security/ir.model.access.csv 
2019-10-13 22:11:38,376 1 INFO odoo odoo.modules.loading: loading web/views/webclient_templates.xml 
2019-10-13 22:11:38,981 1 INFO odoo odoo.modules.loading: loading web/views/report_templates.xml 
2019-10-13 22:11:39,478 1 INFO odoo odoo.modules.loading: loading web/data/res_company.xml 
2019-10-13 22:11:39,495 1 INFO odoo odoo.modules.loading: loading web/data/report_layout.xml 
2019-10-13 22:11:39,858 1 INFO odoo odoo.modules.registry: module base_import: creating or updating database tables 
2019-10-13 22:11:44,198 1 INFO odoo odoo.modules.loading: loading base_import/security/ir.model.access.csv 
2019-10-13 22:11:44,315 1 INFO odoo odoo.modules.loading: loading base_import/views/base_import_templates.xml 
2019-10-13 22:11:44,623 1 INFO odoo odoo.modules.registry: module web_diagram: creating or updating database tables 
2019-10-13 22:11:44,637 1 INFO odoo odoo.modules.loading: loading web_diagram/views/web_diagram_templates.xml 
2019-10-13 22:11:44,956 1 INFO odoo odoo.modules.registry: module web_editor: creating or updating database tables 
2019-10-13 22:11:45,478 1 INFO odoo odoo.modules.loading: loading web_editor/security/ir.model.access.csv 
2019-10-13 22:11:45,504 1 INFO odoo odoo.modules.loading: loading web_editor/views/editor.xml 
2019-10-13 22:11:46,036 1 INFO odoo odoo.modules.loading: loading web_editor/views/iframe.xml 
2019-10-13 22:11:46,104 1 INFO odoo odoo.modules.loading: loading web_editor/views/snippets.xml 
2019-10-13 22:11:46,333 1 INFO odoo odoo.modules.registry: module web_kanban_gauge: creating or updating database tables 
2019-10-13 22:11:46,348 1 INFO odoo odoo.modules.loading: loading web_kanban_gauge/views/web_kanban_gauge_templates.xml 
2019-10-13 22:11:46,703 1 INFO odoo odoo.modules.registry: module web_settings_dashboard: creating or updating database tables 
2019-10-13 22:11:46,770 1 INFO odoo odoo.modules.loading: loading web_settings_dashboard/views/dashboard_views.xml 
2019-10-13 22:11:46,792 1 INFO odoo odoo.modules.loading: loading web_settings_dashboard/views/dashboard_templates.xml 
2019-10-13 22:11:47,137 1 INFO odoo odoo.modules.registry: module web_tour: creating or updating database tables 
2019-10-13 22:11:47,327 1 INFO odoo odoo.modules.loading: loading web_tour/security/ir.model.access.csv 
2019-10-13 22:11:47,358 1 INFO odoo odoo.modules.loading: loading web_tour/security/ir.rule.csv 
2019-10-13 22:11:47,395 1 INFO odoo odoo.modules.loading: loading web_tour/views/tour_templates.xml 
2019-10-13 22:11:47,522 1 INFO odoo odoo.modules.loading: loading web_tour/views/tour_views.xml 
2019-10-13 22:11:47,850 1 INFO odoo odoo.modules.registry: module iap: creating or updating database tables 
2019-10-13 22:11:48,032 1 INFO odoo odoo.modules.loading: loading iap/security/ir.model.access.csv 
2019-10-13 22:11:48,062 1 INFO odoo odoo.modules.loading: loading iap/security/ir_rule.xml 
2019-10-13 22:11:48,089 1 INFO odoo odoo.modules.loading: loading iap/views/assets.xml 
2019-10-13 22:11:48,159 1 INFO odoo odoo.modules.loading: loading iap/views/iap_views.xml 
2019-10-13 22:11:48,300 1 INFO odoo odoo.modules.loading: 9 modules loaded in 12.40s, 0 queries 
2019-10-13 22:11:48,643 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:11:48,902 1 INFO odoo odoo.addons.base.models.res_users: Login successful for db:odoo login:odoo from 172.21.0.1 
2019-10-13 22:11:48,918 1 INFO odoo odoo.modules.registry: Registry changed, signaling through the database 
2019-10-13 22:11:48,926 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:11:48] "POST /web/database/create HTTP/1.1" 303 - 25395 37.583 16.484
2019-10-13 22:11:48,938 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:11:52,771 1 INFO odoo odoo.modules.registry: At least one model cache has been invalidated, signaling through the database. 
2019-10-13 22:11:52,774 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:11:52] "GET /web/ HTTP/1.1" 200 - 605 0.504 3.334
2019-10-13 22:12:04,071 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/ HTTP/1.1" 200 - 294 0.258 0.442
2019-10-13 22:12:04,124 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/246-5086be3/web.assets_common.0.css HTTP/1.1" 200 - 7 0.016 0.015
2019-10-13 22:12:04,158 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/247-a0aa1fa/web.assets_backend.0.css HTTP/1.1" 200 - 4 0.008 0.052
2019-10-13 22:12:04,159 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/248-a0aa1fa/web.assets_backend.1.css HTTP/1.1" 200 - 4 0.014 0.044
2019-10-13 22:12:04,173 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/249-4f411d5/web_editor.summernote.0.css HTTP/1.1" 200 - 4 0.015 0.054
2019-10-13 22:12:04,180 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/250-447701b/web_editor.assets_editor.0.css HTTP/1.1" 200 - 4 0.014 0.057
2019-10-13 22:12:04,192 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/251-5086be3/web.assets_common.js HTTP/1.1" 200 - 4 0.006 0.073
2019-10-13 22:12:04,217 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/252-a0aa1fa/web.assets_backend.js HTTP/1.1" 200 - 4 0.036 0.045
2019-10-13 22:12:04,226 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/254-447701b/web_editor.assets_editor.js HTTP/1.1" 200 - 4 0.015 0.020
2019-10-13 22:12:04,227 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/content/253-4f411d5/web_editor.summernote.js HTTP/1.1" 200 - 4 0.012 0.036
2019-10-13 22:12:04,514 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.000 0.061
2019-10-13 22:12:04,603 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.006 0.011
2019-10-13 22:12:04,621 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:12:04,658 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.008 0.009
2019-10-13 22:12:04,695 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 1 0.001 0.006
2019-10-13 22:12:04,739 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - - - -
2019-10-13 22:12:04,755 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 - 2 0.003 0.009
2019-10-13 22:12:04,811 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 200 - 27 0.028 0.037
2019-10-13 22:12:04,875 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:04] "POST /web/action/load HTTP/1.1" 200 - 49 0.055 0.048
2019-10-13 22:12:05,068 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:05] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.073 0.099
2019-10-13 22:12:05,165 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:05] "GET /web/static/lib/jquery.touchSwipe/jquery.touchSwipe.js HTTP/1.1" 200 - - - -
2019-10-13 22:12:05,184 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:05] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.011 0.011
2019-10-13 22:12:18,129 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:18] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.004 0.011
2019-10-13 22:12:21,352 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:21] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.006 0.004
2019-10-13 22:12:24,475 1 INFO odoo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2019-10-13 22:12:24,501 1 INFO odoo odoo.addons.base.models.ir_attachment: filestore gc 253 checked, 0 removed 
2019-10-13 22:12:24,517 1 INFO odoo odoo.addons.base.models.ir_autovacuum: GC'd 0 user log entries 
2019-10-13 22:12:29,521 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:12:29,522 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:12:29,523 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:12:30,077 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:12:30,096 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:12:30,260 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:12:30,262 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:12:31,270 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:12:31,298 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:12:31,300 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:12:31,417 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:12:31,418 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:12:31,477 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:12:31,841 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:12:31,847 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2019-10-13 22:12:31,861 1 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 7 and record, line 12, column 14
2019-10-13 22:12:31,865 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 7 and record, line 12, column 14
2019-10-13 22:12:31,890 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:12:31,914 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:12:31,925 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:12:31,953 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:12:32,009 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:12:32,012 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:32] "POST /web/dataset/call_button HTTP/1.1" 200 - 781 0.933 1.573
2019-10-13 22:12:32,032 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:12:32] "GET /web/static/src/xml/dialog.xml HTTP/1.1" 200 - - - -
2019-10-13 22:14:24,238 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:14:24,278 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:14:24,278 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:14:24,279 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:14:24,831 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:14:24,848 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:14:25,011 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:14:25,014 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:14:26,044 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:14:26,072 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:14:26,075 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:14:26,129 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:14:26,130 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:14:26,185 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:14:26,483 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:14:26,489 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2019-10-13 22:14:26,501 1 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:14:26,502 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:14:26,518 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:14:26,541 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:14:26,548 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:14:26,575 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:14:26,628 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:14:26,631 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:26] "POST /web/dataset/call_button HTTP/1.1" 200 - 789 0.929 1.466
2019-10-13 22:14:32,187 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:14:32,187 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 22:14:45,823 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 22:14:45,823 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 22:14:45,824 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 22:14:45,824 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 22:14:46,028 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 22:14:46,365 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 22:14:46,365 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 22:14:46,366 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 22:14:46,627 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 22:14:46,736 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0f839b888d9f:8069 
2019-10-13 22:14:46,857 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 22:14:46,901 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:14:46,924 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:14:46,934 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:14:46,993 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 22:14:47,218 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:14:47,224 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:14:48,042 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "GET /web/ HTTP/1.1" 200 - 321 0.282 0.900
2019-10-13 22:14:48,333 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.001 0.059
2019-10-13 22:14:48,411 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.006 0.011
2019-10-13 22:14:48,459 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:14:48,466 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.004 0.007
2019-10-13 22:14:48,640 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 56 0.052 0.098
2019-10-13 22:14:48,756 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 200 - 27 0.035 0.027
2019-10-13 22:14:48,800 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:48] "POST /web/action/load HTTP/1.1" 200 - 49 0.051 0.056
2019-10-13 22:14:49,019 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:49] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.091 0.107
2019-10-13 22:14:49,106 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:49] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.007 0.013
2019-10-13 22:14:51,715 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:51] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.004 0.011
2019-10-13 22:14:52,939 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:52] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.005 0.004
2019-10-13 22:14:55,620 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:14:55,620 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:14:55,622 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:14:56,115 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:14:56,135 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:14:56,297 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:14:56,299 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:14:57,342 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:14:57,370 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:14:57,373 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:14:57,430 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:14:57,430 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:14:57,487 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:14:57,871 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:14:57,877 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2019-10-13 22:14:57,888 1 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:14:57,890 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:14:57,907 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:14:57,928 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:14:57,936 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:14:57,962 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:14:58,017 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:14:58,020 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:14:58] "POST /web/dataset/call_button HTTP/1.1" 200 - 781 0.933 1.477
2019-10-13 22:15:02,083 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:15:02,083 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2019-10-13 22:15:26,291 1 INFO ? odoo: Odoo version 12.0-20190816 
2019-10-13 22:15:26,291 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2019-10-13 22:15:26,291 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2019-10-13 22:15:26,292 1 INFO ? odoo: database: odoo@db:5432 
2019-10-13 22:15:26,419 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2019-10-13 22:15:26,571 1 INFO ? odoo.service.server: Watching addons folder /var/lib/odoo/addons/12.0 
2019-10-13 22:15:26,572 1 INFO ? odoo.service.server: Watching addons folder /mnt/extra-addons 
2019-10-13 22:15:26,572 1 INFO ? odoo.service.server: Watching addons folder /usr/lib/python3/dist-packages/odoo/addons 
2019-10-13 22:15:26,822 1 INFO ? odoo.service.server: AutoReload watcher running with watchdog 
2019-10-13 22:15:26,840 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0f839b888d9f:8069 
2019-10-13 22:15:37,457 1 INFO ? odoo.http: HTTP Configuring static files 
2019-10-13 22:15:37,484 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:15:37,508 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:15:37,516 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:15:37,575 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.06s, 0 queries 
2019-10-13 22:15:37,800 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:15:37,805 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:15:38,597 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/ HTTP/1.1" 200 - 321 0.270 0.867
2019-10-13 22:15:38,657 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/247-a0aa1fa/web.assets_backend.0.css HTTP/1.1" 200 - 7 0.011 0.023
2019-10-13 22:15:38,658 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/246-5086be3/web.assets_common.0.css HTTP/1.1" 200 - 7 0.018 0.019
2019-10-13 22:15:38,690 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/249-4f411d5/web_editor.summernote.0.css HTTP/1.1" 200 - 4 0.011 0.049
2019-10-13 22:15:38,696 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/250-447701b/web_editor.assets_editor.0.css HTTP/1.1" 200 - 4 0.010 0.052
2019-10-13 22:15:38,706 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/248-a0aa1fa/web.assets_backend.1.css HTTP/1.1" 200 - 4 0.018 0.061
2019-10-13 22:15:38,710 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/251-5086be3/web.assets_common.js HTTP/1.1" 200 - 4 0.011 0.062
2019-10-13 22:15:38,736 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/252-a0aa1fa/web.assets_backend.js HTTP/1.1" 200 - 4 0.013 0.050
2019-10-13 22:15:38,740 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/253-4f411d5/web_editor.summernote.js HTTP/1.1" 200 - 4 0.023 0.040
2019-10-13 22:15:38,750 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/content/254-447701b/web_editor.assets_editor.js HTTP/1.1" 200 - 4 0.007 0.031
2019-10-13 22:15:38,999 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:38] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.000 0.082
2019-10-13 22:15:39,050 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:15:39,058 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.012 0.013
2019-10-13 22:15:39,085 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.007 0.009
2019-10-13 22:15:39,122 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 1 0.001 0.006
2019-10-13 22:15:39,158 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "GET /web/static/lib/fontawesome/fonts/fontawesome-webfont.woff2?v=4.7.0 HTTP/1.1" 200 - - - -
2019-10-13 22:15:39,215 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 304 - 27 0.038 0.023
2019-10-13 22:15:39,276 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/action/load HTTP/1.1" 200 - 49 0.061 0.052
2019-10-13 22:15:39,497 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.096 0.104
2019-10-13 22:15:39,587 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:39] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.012 0.011
2019-10-13 22:15:43,092 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:43] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.004 0.011
2019-10-13 22:15:44,121 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:44] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.006 0.004
2019-10-13 22:15:46,636 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:15:46,636 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:15:46,637 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:15:47,104 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:15:47,126 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:15:47,293 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:15:47,296 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:15:48,336 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:15:48,364 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:15:48,366 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:15:48,422 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:15:48,422 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:15:48,476 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:15:48,951 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:15:48,958 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2019-10-13 22:15:48,974 1 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:15:48,976 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 848, in convert_xml_import
    doc = etree.parse(xmlfile)
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81110)
  File "src/lxml/parser.pxi", line 1832, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:118109)
  File "src/lxml/parser.pxi", line 1852, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:118392)
  File "src/lxml/parser.pxi", line 1747, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:117180)
  File "src/lxml/parser.pxi", line 1162, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:111907)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 635, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105664)
  File "/mnt/extra-addons/sccc/views/views.xml", line 12
lxml.etree.XMLSyntaxError: Opening and ending tag mismatch: field line 6 and record, line 12, column 14
2019-10-13 22:15:49,004 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:15:49,027 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:15:49,035 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:15:49,065 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:15:49,131 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:15:49,134 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:15:49] "POST /web/dataset/call_button HTTP/1.1" 200 - 781 1.019 1.491
2019-10-13 22:17:06,487 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:17:07,263 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "GET /web/ HTTP/1.1" 200 - 311 0.279 0.500
2019-10-13 22:17:07,633 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.000 0.112
2019-10-13 22:17:07,688 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:17:07,692 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.011 0.012
2019-10-13 22:17:07,718 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.004 0.008
2019-10-13 22:17:07,752 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 1 0.001 0.004
2019-10-13 22:17:07,844 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 304 - 27 0.035 0.024
2019-10-13 22:17:07,901 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:07] "POST /web/action/load HTTP/1.1" 200 - 49 0.053 0.054
2019-10-13 22:17:08,154 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:08] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.111 0.123
2019-10-13 22:17:08,236 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:08] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.008 0.010
2019-10-13 22:17:10,522 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:10] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.004 0.013
2019-10-13 22:17:11,972 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:11] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.005 0.004
2019-10-13 22:17:14,367 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:17:14,368 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:17:14,370 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:17:14,878 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:17:14,897 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:17:15,060 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:17:15,062 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:17:16,099 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:17:16,128 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:17:16,131 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:17:16,184 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:17:16,185 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:17:16,239 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:17:16,544 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:17:16,581 1 INFO odoo odoo.addons.base.models.ir_ui_view: Field `value` does not exist

Error context:
View `room list tree`
[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a] 
2019-10-13 22:17:16,586 1 WARNING odoo odoo.modules.loading: Transient module states were reset 
2019-10-13 22:17:16,624 1 ERROR odoo odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1106, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `value` does not exist

Error context:
View `room list tree`
[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `value` does not exist\n\nError context:\nView `room list tree`\n[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `value` does not exist

Error context:
View `room list tree`
[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]
None" while parsing /mnt/extra-addons/sccc/views/views.xml:3, near
<record model="ir.ui.view" id="room_tree_view">
      <field name="name">room list tree</field>
      <field name="model">sccc.room</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="value"/>
        </tree>
      </field>
    </record>
2019-10-13 22:17:16,631 1 ERROR odoo odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1108, in _validate_fields
    check(self)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 351, in _check_xml
    self.postprocess_and_fields(view.model, view_doc, view.id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1106, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 548, in raise_view_error
    raise ValueError(message)
ValueError: Field `value` does not exist

Error context:
View `room list tree`
[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nField `value` does not exist\n\nError context:\nView `room list tree`\n[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 346, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 941, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 519, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 966, in call_button
    action = self._call_kw(model, method, args, {})
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-61>", line 2, in button_immediate_install
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 445, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_module.py", line 561, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 802, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 865, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 755, in parse
    self.parse(rec, mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 764, in parse
    exc_info[2]
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 758, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/usr/lib/python3/dist-packages/odoo/tools/convert.py", line 663, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3865, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3779, in _load_records_create
    return self.create(values)
  File "<decorator-gen-32>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 428, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 452, in _model_create_multi
    return create(self, arg)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3596, in create
    fields[0].determine_inverse(batch_recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1117, in determine_inverse
    getattr(records, self.inverse)()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 444, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3321, in write
    self._write(store_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3457, in _write
    self._validate_fields(vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1112, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Field `value` does not exist

Error context:
View `room list tree`
[view_id: 228, xml_id: n/a, model: sccc.room, parent_id: n/a]
None" while parsing /mnt/extra-addons/sccc/views/views.xml:3, near
<record model="ir.ui.view" id="room_tree_view">
      <field name="name">room list tree</field>
      <field name="model">sccc.room</field>
      <field name="arch" type="xml">
        <tree>
          <field name="name"/>
          <field name="value"/>
        </tree>
      </field>
    </record>
2019-10-13 22:17:16,650 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:17:16,673 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:17:16,681 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:17:16,707 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:17:16,759 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:17:16,762 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:16] "POST /web/dataset/call_button HTTP/1.1" 200 - 803 0.947 1.460
2019-10-13 22:17:48,576 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:17:49,329 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "GET /web/ HTTP/1.1" 200 - 311 0.275 0.481
2019-10-13 22:17:49,547 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.001 0.063
2019-10-13 22:17:49,603 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "GET /web/static/src/img/favicon.ico HTTP/1.1" 200 - - - -
2019-10-13 22:17:49,604 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.009 0.012
2019-10-13 22:17:49,629 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.004 0.007
2019-10-13 22:17:49,663 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 1 0.000 0.005
2019-10-13 22:17:49,756 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 304 - 27 0.037 0.024
2019-10-13 22:17:49,807 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:49] "POST /web/action/load HTTP/1.1" 200 - 49 0.049 0.054
2019-10-13 22:17:50,034 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:50] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.102 0.109
2019-10-13 22:17:50,123 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:50] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.006 0.011
2019-10-13 22:17:52,802 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:52] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.005 0.011
2019-10-13 22:17:53,786 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:53] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.005 0.004
2019-10-13 22:17:55,400 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_immediate_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:17:55,400 1 INFO odoo odoo.addons.base.models.ir_module: User #2 triggered module installation 
2019-10-13 22:17:55,402 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on ['sccc'] to user odoo #2 via 172.21.0.1 
2019-10-13 22:17:55,898 1 INFO odoo odoo.modules.loading: loading 1 modules... 
2019-10-13 22:17:55,919 1 INFO odoo odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries 
2019-10-13 22:17:56,080 1 INFO odoo odoo.modules.loading: updating modules list 
2019-10-13 22:17:56,082 1 INFO odoo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via 172.21.0.1 
2019-10-13 22:17:57,163 1 INFO odoo odoo.modules.loading: loading 9 modules... 
2019-10-13 22:17:57,191 1 INFO odoo odoo.modules.loading: 9 modules loaded in 0.03s, 0 queries 
2019-10-13 22:17:57,193 1 INFO odoo odoo.modules.loading: loading 10 modules... 
2019-10-13 22:17:57,247 1 WARNING odoo odoo.models: The model sccc.location has no _description 
2019-10-13 22:17:57,247 1 WARNING odoo odoo.models: The model sccc.room has no _description 
2019-10-13 22:17:57,300 1 INFO odoo odoo.modules.registry: module sccc: creating or updating database tables 
2019-10-13 22:17:57,672 1 INFO odoo odoo.modules.loading: loading sccc/views/views.xml 
2019-10-13 22:17:57,708 1 INFO odoo odoo.modules.loading: loading sccc/views/templates.xml 
2019-10-13 22:17:57,785 1 INFO odoo odoo.modules.loading: 10 modules loaded in 0.59s, 0 queries 
2019-10-13 22:17:57,849 1 WARNING odoo odoo.modules.loading: The model sccc.location has no access rules, consider adding one. E.g. access_sccc_location,access_sccc_location,model_sccc_location,base.group_user,1,0,0,0 
2019-10-13 22:17:57,850 1 WARNING odoo odoo.modules.loading: The model sccc.room has no access rules, consider adding one. E.g. access_sccc_room,access_sccc_room,model_sccc_room,base.group_user,1,0,0,0 
2019-10-13 22:17:58,104 1 INFO odoo odoo.modules.loading: Modules loaded. 
2019-10-13 22:17:58,199 1 INFO odoo odoo.addons.base.models.ir_module: getting next ir.actions.todo() 
2019-10-13 22:17:58,211 1 INFO odoo odoo.modules.registry: Registry changed, signaling through the database 
2019-10-13 22:17:58,215 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:58] "POST /web/dataset/call_button HTTP/1.1" 200 - 1062 1.227 1.602
2019-10-13 22:17:58,246 1 INFO odoo odoo.addons.base.models.ir_http: Generating routing map 
2019-10-13 22:17:59,031 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "GET /web HTTP/1.1" 200 - 311 0.271 0.516
2019-10-13 22:17:59,211 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "GET /web/webclient/qweb?mods=base,web,base_import,web_settings_dashboard,iap,web_diagram,web_editor,web_kanban_gauge,web_tour HTTP/1.1" 200 - 1 0.001 0.061
2019-10-13 22:17:59,256 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/dataset/call HTTP/1.1" 200 - 12 0.008 0.015
2019-10-13 22:17:59,282 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/webclient/translations HTTP/1.1" 200 - 6 0.004 0.008
2019-10-13 22:17:59,309 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/dataset/call_kw/ir.ui.menu/load_menus HTTP/1.1" 200 - 1 0.001 0.006
2019-10-13 22:17:59,346 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/dataset/call_kw/res.users/read HTTP/1.1" 200 - 2 0.001 0.009
2019-10-13 22:17:59,392 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "GET /web/image?model=res.users&field=image_small&id=2 HTTP/1.1" 304 - 27 0.035 0.026
2019-10-13 22:17:59,446 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/action/load HTTP/1.1" 200 - 49 0.043 0.048
2019-10-13 22:17:59,661 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/dataset/call_kw/ir.module.module/load_views HTTP/1.1" 200 - 95 0.087 0.111
2019-10-13 22:17:59,737 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:17:59] "POST /web/dataset/search_read HTTP/1.1" 200 - 5 0.007 0.012
2019-10-13 22:18:05,003 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:05] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.004 0.008
2019-10-13 22:18:05,059 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:05] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.004 0.008
2019-10-13 22:18:14,240 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:14] "POST /web/dataset/search_read HTTP/1.1" 200 - 4 0.004 0.012
2019-10-13 22:18:17,352 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:17] "POST /web/dataset/search_read HTTP/1.1" 200 - 3 0.005 0.004
2019-10-13 22:18:25,880 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:25] "POST /web/dataset/call_kw/ir.module.module/read HTTP/1.1" 200 - 11 0.013 0.027
2019-10-13 22:18:25,923 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:25] "POST /web/dataset/call_kw/ir.module.module.dependency/read HTTP/1.1" 200 - 4 0.003 0.009
2019-10-13 22:18:25,952 1 INFO odoo werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:25] "POST /web/dataset/call_kw/ir.module.category/name_search HTTP/1.1" 200 - 5 0.005 0.016
2019-10-13 22:18:26,061 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:26] "GET /base/static/src/css/description.css HTTP/1.1" 200 - - - -
2019-10-13 22:18:26,064 1 INFO ? werkzeug: 172.21.0.1 - - [13/Oct/2019 22:18:26] "GET /web/static/src/img/form_sheetbg.png HTTP/1.1" 200 - - - -
2019-10-13 22:18:44,315 1 INFO ? odoo.service.server: Initiating shutdown 
2019-10-13 22:18:44,315 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
